const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('Creating Next.js app...');
execSync('npx create-next-app@latest sridhar-site --typescript --tailwind --app --no-src-dir --import-alias "@/*" --eslint --use-npm', { stdio: 'inherit' });

process.chdir('sridhar-site');
console.log('Installing framer-motion...');
execSync('npm install framer-motion', { stdio: 'inherit' });

fs.mkdirSync('components', { recursive: true });
fs.mkdirSync('public/images', { recursive: true });

const files = {
  "app/layout.tsx": "import type { Metadata } from \"next\";\nimport { Space_Grotesk, Inter } from \"next/font/google\";\nimport \"./globals.css\";\n\nconst spaceGrotesk = Space_Grotesk({\n  variable: \"--font-display\",\n  subsets: [\"latin\"],\n  weight: [\"500\", \"700\"],\n});\n\nconst inter = Inter({\n  variable: \"--font-body\",\n  subsets: [\"latin\"],\n  weight: [\"400\", \"500\", \"600\"],\n});\n\nexport const metadata: Metadata = {\n  title: \"Sridhar\",\n  description: \"Sridhar \u2014 builder, student, founder of NxtStepEdu.\",\n};\n\nexport default function RootLayout({ children }: LayoutProps<\"/\">) {\n  return (\n    <html\n      lang=\"en\"\n      className={`${spaceGrotesk.variable} ${inter.variable} h-full antialiased`}\n    >\n      <body className=\"min-h-full flex flex-col bg-[#150F2E] text-[#FDF9FF]\">{children}</body>\n    </html>\n  );\n}\n",
  "app/globals.css": "@import \"tailwindcss\";\n\n@theme inline {\n  --font-display: var(--font-display);\n  --font-body: var(--font-body);\n}\n\n@media (prefers-reduced-motion: reduce) {\n  *, *::before, *::after {\n    animation-duration: 0.01ms !important;\n    animation-iteration-count: 1 !important;\n    transition-duration: 0.01ms !important;\n  }\n}\n\nhtml {\n  scroll-behavior: smooth;\n}\n\nbody {\n  font-family: var(--font-body), sans-serif;\n  overflow-x: hidden;\n}\n\n.font-display {\n  font-family: var(--font-display), sans-serif;\n}\n",
  "app/page.tsx": "import Blob from \"@/components/Blob\";\nimport Hero from \"@/components/Hero\";\nimport Gallery from \"@/components/Gallery\";\nimport Quotes from \"@/components/Quotes\";\nimport Footer from \"@/components/Footer\";\n\nexport default function Home() {\n  return (\n    <main className=\"relative\">\n      <Blob />\n      <Hero />\n      <Gallery />\n      <Quotes />\n      <Footer />\n    </main>\n  );\n}\n",
  "components/Blob.tsx": "\"use client\";\n\nimport { motion } from \"framer-motion\";\n\nexport default function Blob() {\n  return (\n    <div className=\"pointer-events-none fixed inset-0 -z-10 overflow-hidden\">\n      <motion.div\n        className=\"absolute -top-1/4 -left-1/4 h-[70vmax] w-[70vmax] rounded-full opacity-60 blur-3xl\"\n        style={{\n          background:\n            \"radial-gradient(circle at 30% 30%, #FF3EA5, transparent 60%), radial-gradient(circle at 70% 70%, #7C3AED, transparent 60%)\",\n        }}\n        animate={{\n          borderRadius: [\n            \"60% 40% 30% 70%/60% 30% 70% 40%\",\n            \"30% 60% 70% 40%/50% 60% 30% 60%\",\n            \"60% 40% 30% 70%/60% 30% 70% 40%\",\n          ],\n          x: [0, 60, 0],\n          y: [0, 40, 0],\n        }}\n        transition={{\n          duration: 22,\n          repeat: Infinity,\n          ease: \"easeInOut\",\n        }}\n      />\n      <motion.div\n        className=\"absolute -bottom-1/4 -right-1/4 h-[60vmax] w-[60vmax] rounded-full opacity-40 blur-3xl\"\n        style={{\n          background:\n            \"radial-gradient(circle at 40% 40%, #FFD93D, transparent 60%), radial-gradient(circle at 60% 60%, #FF3EA5, transparent 65%)\",\n        }}\n        animate={{\n          borderRadius: [\n            \"40% 60% 60% 40%/40% 40% 60% 60%\",\n            \"60% 40% 40% 60%/60% 60% 40% 40%\",\n            \"40% 60% 60% 40%/40% 40% 60% 60%\",\n          ],\n          x: [0, -50, 0],\n          y: [0, -30, 0],\n        }}\n        transition={{\n          duration: 26,\n          repeat: Infinity,\n          ease: \"easeInOut\",\n        }}\n      />\n    </div>\n  );\n}\n",
  "components/Hero.tsx": "\"use client\";\n\nimport { motion } from \"framer-motion\";\n\nconst letters = \"SRIDHAR\".split(\"\");\n\nexport default function Hero() {\n  return (\n    <section className=\"relative flex min-h-screen flex-col items-center justify-center px-6 text-center\">\n      <motion.p\n        initial={{ opacity: 0, y: 10 }}\n        animate={{ opacity: 1, y: 0 }}\n        transition={{ delay: 0.1, duration: 0.5 }}\n        className=\"mb-4 text-sm font-medium tracking-wide text-[#FFD93D]\"\n      >\n        builder, student, chronic idea-haver\n      </motion.p>\n\n      <h1 className=\"font-display flex flex-wrap justify-center text-[16vw] leading-[0.85] font-bold sm:text-[9rem]\">\n        {letters.map((letter, i) => (\n          <motion.span\n            key={i}\n            initial={{ opacity: 0, y: 60, rotate: -8 }}\n            animate={{ opacity: 1, y: 0, rotate: 0 }}\n            transition={{\n              delay: 0.15 + i * 0.06,\n              duration: 0.6,\n              ease: [0.22, 1, 0.36, 1],\n            }}\n            className=\"inline-block\"\n            style={{\n              color: i % 2 === 0 ? \"#FDF9FF\" : \"#FF3EA5\",\n            }}\n          >\n            {letter}\n          </motion.span>\n        ))}\n      </h1>\n\n      <motion.p\n        initial={{ opacity: 0 }}\n        animate={{ opacity: 1 }}\n        transition={{ delay: 1.0, duration: 0.6 }}\n        className=\"mt-6 max-w-md text-base text-[#FDF9FF]/70\"\n      >\n        Co-founder of NxtStepEdu. Building school software and internships\n        that actually teach something. Currently researching at IIM Vizag.\n      </motion.p>\n\n      <motion.div\n        initial={{ opacity: 0 }}\n        animate={{ opacity: 1 }}\n        transition={{ delay: 1.3, duration: 0.6 }}\n        className=\"mt-14 flex flex-col items-center gap-2 text-[#FDF9FF]/50\"\n      >\n        <span className=\"text-xs\">scroll</span>\n        <motion.div\n          animate={{ y: [0, 8, 0] }}\n          transition={{ duration: 1.6, repeat: Infinity, ease: \"easeInOut\" }}\n          className=\"h-8 w-[1px] bg-[#FDF9FF]/40\"\n        />\n      </motion.div>\n    </section>\n  );\n}\n",
  "components/Gallery.tsx": "\"use client\";\n\nimport { motion } from \"framer-motion\";\nimport Image from \"next/image\";\n\nconst photos = [\n  { src: \"/images/placeholder1.jpg\", rotate: -6, span: \"col-span-2 row-span-2\" },\n  { src: \"/images/placeholder2.jpg\", rotate: 4, span: \"col-span-1 row-span-1\" },\n  { src: \"/images/placeholder3.jpg\", rotate: -3, span: \"col-span-1 row-span-1\" },\n  { src: \"/images/placeholder4.jpg\", rotate: 5, span: \"col-span-1 row-span-2\" },\n  { src: \"/images/placeholder5.jpg\", rotate: -5, span: \"col-span-2 row-span-1\" },\n  { src: \"/images/placeholder6.jpg\", rotate: 3, span: \"col-span-1 row-span-1\" },\n];\n\nexport default function Gallery() {\n  return (\n    <section className=\"relative px-6 py-28 sm:px-12\">\n      <motion.h2\n        initial={{ opacity: 0, y: 20 }}\n        whileInView={{ opacity: 1, y: 0 }}\n        viewport={{ once: true, margin: \"-100px\" }}\n        transition={{ duration: 0.6 }}\n        className=\"font-display mb-12 text-4xl font-bold sm:text-6xl\"\n      >\n        a few frames\n      </motion.h2>\n\n      <div className=\"grid grid-cols-2 gap-4 sm:grid-cols-4 sm:gap-6\">\n        {photos.map((photo, i) => (\n          <motion.div\n            key={photo.src}\n            initial={{ opacity: 0, scale: 0.9, rotate: 0 }}\n            whileInView={{ opacity: 1, scale: 1, rotate: photo.rotate }}\n            viewport={{ once: true, margin: \"-60px\" }}\n            transition={{ duration: 0.5, delay: (i % 4) * 0.08 }}\n            whileHover={{ rotate: 0, scale: 1.03 }}\n            className={`${photo.span} relative aspect-[4/5] overflow-hidden rounded-2xl shadow-2xl shadow-black/40`}\n          >\n            <Image\n              src={photo.src}\n              alt=\"\"\n              fill\n              className=\"object-cover\"\n              sizes=\"(max-width: 640px) 50vw, 25vw\"\n            />\n          </motion.div>\n        ))}\n      </div>\n    </section>\n  );\n}\n",
  "components/Quotes.tsx": "\"use client\";\n\nimport { motion } from \"framer-motion\";\n\nconst thoughts = [\n  { label: \"thought 1\", text: \"Replace this with a real line of yours.\" },\n  { label: \"thought 2\", text: \"Replace this with a real line of yours.\" },\n  { label: \"thought 3\", text: \"Replace this with a real line of yours.\" },\n];\n\nconst colors = [\"#FF3EA5\", \"#FFD93D\", \"#7C3AED\"];\n\nexport default function Quotes() {\n  return (\n    <section className=\"relative flex flex-col gap-24 px-6 py-32 sm:px-12\">\n      {thoughts.map((t, i) => (\n        <motion.div\n          key={t.label}\n          initial={{ opacity: 0, x: i % 2 === 0 ? -40 : 40 }}\n          whileInView={{ opacity: 1, x: 0 }}\n          viewport={{ once: true, margin: \"-120px\" }}\n          transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}\n          className={`max-w-3xl ${i % 2 === 0 ? \"self-start text-left\" : \"self-end text-right\"}`}\n        >\n          <p className=\"mb-3 text-xs font-medium tracking-wide text-[#FDF9FF]/40\">\n            {t.label}\n          </p>\n          <p\n            className=\"font-display text-3xl leading-tight font-medium sm:text-5xl\"\n            style={{ color: colors[i % colors.length] }}\n          >\n            {t.text}\n          </p>\n        </motion.div>\n      ))}\n    </section>\n  );\n}\n",
  "components/Footer.tsx": "export default function Footer() {\n  return (\n    <footer className=\"relative flex flex-col items-center gap-4 px-6 py-20 text-center\">\n      <p className=\"font-display text-2xl font-bold\">let's build something</p>\n      <div className=\"flex gap-6 text-sm text-[#FDF9FF]/60\">\n        <a href=\"mailto:you@example.com\" className=\"hover:text-[#FF3EA5]\">\n          email\n        </a>\n        <a href=\"#\" className=\"hover:text-[#FF3EA5]\">\n          github\n        </a>\n        <a href=\"#\" className=\"hover:text-[#FF3EA5]\">\n          linkedin\n        </a>\n      </div>\n      <p className=\"mt-6 text-xs text-[#FDF9FF]/30\">sridhar-six.vercel.app</p>\n    </footer>\n  );\n}\n"
};

for (const [filePath, content] of Object.entries(files)) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log('wrote', filePath);
}

// generate simple placeholder images using solid PNGs disguised as jpg (browser will still render fine only if actual jpg; instead write valid 1x1 colored JPEGs)
console.log('Note: add your own images to public/images/ named placeholder1.jpg ... placeholder6.jpg');

console.log('');
console.log('Done! Starting dev server at http://localhost:3000 ...');
execSync('npm run dev', { stdio: 'inherit' });